export const MAP_EVENT_NAMES = [
	'add',
	'remove',
	'load',
	'unload',
	'viewreset',
	'movestart',
	'move',
	'moveend',
	'dragstart',
	'drag',
	'dragend',
	'predrag',
	'zoomlevelschange',
	'zoomstart',
	'zoom',
	'zoomanim',
	'zoomend',
	'resize',
	'autopanstart',
	'layeradd',
	'layerremove',
	'baselayerchange',
	'overlayadd',
	'overlayremove',
	'locationfound',
	'locationerror',
	'click',
	'dblclick',
	'mousedown',
	'mouseup',
	'mousemove',
	'mouseover',
	'mouseout',
	'contextmenu',
	'preclick',
	'error',
	'keydown',
	'keypress',
	'keyup',
	// Include tile events because this component creates a tile layer
	'tileload',
	'tileloadstart',
	'tileunload',
	'tileerror',
	// Include popup/tooltip events (bubble from map)
	'popupopen',
	'popupclose',
	'tooltipopen',
	'tooltipclose',
	// Internal update event
	'update'
] as const satisfies readonly (keyof import('leaflet').LeafletEventHandlerFnMap)[];
